version: "3"

services:

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: ruyu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 1488:1488
      - 9229:9229
    command: npm run start
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata:
